# Generated by Django 5.0.3 on 2024-04-01 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Имя на русском')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Имя на кыргызском')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/category', verbose_name='Фото категории')),
                ('parentCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.category', verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории запчастей',
            },
        ),
    ]
