# Generated by Django 5.0.3 on 2024-04-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='additional_ky',
        ),
        migrations.AddField(
            model_name='part',
            name='location',
            field=models.TextField(default='Бишкек', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.IntegerField(default=1500, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
