# Generated by Django 5.0.3 on 2024-04-01 08:55

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefCarFuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Имя на русском')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Имя на кыргызском')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Топливо',
                'verbose_name_plural': 'Топливы',
            },
        ),
        migrations.CreateModel(
            name='RefCarGearBoxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Имя на русском')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Имя на кыргызском')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Коробка передатчик',
                'verbose_name_plural': 'Коробка передатчик',
            },
        ),
        migrations.CreateModel(
            name='RefCarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Имя на русском')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Имя на кыргызском')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('emblems', models.ImageField(blank=True, null=True, upload_to='images/emblems', verbose_name='Эмблема машин')),
            ],
            options={
                'verbose_name': 'Марка машина',
                'verbose_name_plural': 'Марки машины',
            },
        ),
        migrations.CreateModel(
            name='RefCarSteeringWheelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Имя на русском')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Имя на кыргызском')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Руль',
                'verbose_name_plural': 'Рулей',
            },
        ),
        migrations.CreateModel(
            name='RefCarWheelDriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Имя на русском')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Имя на кыргызском')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Привод',
                'verbose_name_plural': 'Приводы',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/ref', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reference.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии моделей',
            },
        ),
        migrations.CreateModel(
            name='RefCarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Имя на русском')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Имя на кыргызском')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('year', models.DateTimeField(verbose_name='Год выпуска')),
                ('engine_size', models.CharField(max_length=10, verbose_name='Обьем двигателя')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.refcarfueltype', verbose_name='Тип топливо')),
                ('gearbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.refcargearboxtype', verbose_name='Коробка передатчик')),
                ('mark_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.refcarmark', verbose_name='Марка ID')),
                ('steering_wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.refcarsteeringwheeltype', verbose_name='Руль')),
                ('wheel_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.refcarwheeldrivetype', verbose_name='Привод')),
            ],
            options={
                'verbose_name': 'Модель машина',
                'verbose_name_plural': 'Модели машины',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Имя на русском')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Имя на кыргызском')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('code', models.CharField(max_length=100, verbose_name='Код машины')),
                ('additional_ru', ckeditor.fields.RichTextField(verbose_name='Информации RU')),
                ('additional_ky', ckeditor.fields.RichTextField(verbose_name='Информации KG')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.category')),
                ('image_id', models.ManyToManyField(to='reference.image', verbose_name='Фото продукт')),
                ('car_model_id', models.ManyToManyField(to='reference.refcarmodel', verbose_name='Модель машины')),
            ],
            options={
                'verbose_name': 'Продукт / запчасть',
                'verbose_name_plural': 'Запчасты',
            },
        ),
    ]
