# Generated by Django 5.0.3 on 2024-04-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_refcarfueltype_refcargearboxtype_refcarmark_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefCarSteeringWheelType',
            new_name='RefCarFuel',
        ),
        migrations.RenameModel(
            old_name='RefCarWheelDriveType',
            new_name='RefCarGearBox',
        ),
        migrations.RenameModel(
            old_name='RefCarGearBoxType',
            new_name='RefCarSteeringWheel',
        ),
        migrations.RenameModel(
            old_name='RefCarFuelType',
            new_name='RefCarWheelDrive',
        ),
        migrations.AlterModelOptions(
            name='refcarfuel',
            options={'verbose_name': 'Топливо', 'verbose_name_plural': 'Топливы'},
        ),
        migrations.AlterModelOptions(
            name='refcargearbox',
            options={'verbose_name': 'Коробка передатчик', 'verbose_name_plural': 'Коробка передатчик'},
        ),
        migrations.AlterModelOptions(
            name='refcarsteeringwheel',
            options={'verbose_name': 'Руль', 'verbose_name_plural': 'Рулей'},
        ),
        migrations.AlterModelOptions(
            name='refcarwheeldrive',
            options={'verbose_name': 'Привод', 'verbose_name_plural': 'Приводы'},
        ),
    ]
