# Generated by Django 5.0.3 on 2024-04-09 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_remove_part_additional_ky_part_location_part_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefCarBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Имя на русском')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Тип кузовы',
            },
        ),
        migrations.AlterField(
            model_name='refcarmodel',
            name='engine_size',
            field=models.CharField(max_length=10, verbose_name='Объем двигателя'),
        ),
        migrations.AlterField(
            model_name='refcarmodel',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.refcarfuel', verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='refcarmodel',
            name='gearbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.refcargearbox', verbose_name='Коробка передач'),
        ),
    ]
