# Generated by Django 5.0.3 on 2024-04-09 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_refcarbody_alter_refcarmodel_engine_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refcarmodel',
            name='car_body',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference.refcarbody', verbose_name='Тип кузова'),
            preserve_default=False,
        ),
    ]
